# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: The Geek machine
title: The geek machine
email: vintz@geekmachine.info
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.geekmachine.info" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  vintz

# Build settings
#theme: minima
remote_theme: thiagorossener/jekflix-template
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# ###### THEME CONFIG ###### 


show_hero: true

show_time_bar: true
show_modal_on_finish_post: true

menu:
  - title: Accueil
    url: /
  - title: A propos
    url: /about
  - title: Feed
    url: /feed.xml

translations:
  text:
    to_read: "de lecture"
    new_post: "Nouveau post"
    see_also: "See also"
    search: "Recherche"
    author: "Auteur"
    share: "Partager"
    comments: "Commentaires"
  button:
    read_now: "Lecture"
    share_on_twitter: "Partager sur twitter"
    share_on_facebook: "Partager sur Facebook"
  pagination:
    page: "Page"
    of: "of"
    next_page: "Suivant"
    next_post: "Précedent"
  recommendation:
    text: "Voulez-vous lire un autre article?"
    back_btn: "Retour en haut de page"
  error_404:
    title: "Il n'y a rien à cet endroit. Essaie encore... ;-)"
    message: "I'm sorry. We couldn't find the page you are looking for."
    image_alt: "404 - Page not found"
  contact:
    title: "Talk to me"
    subject: "New contact!"
    submit_btn: "Send"
    placeholders:
      name: "Your name"
      email: "Your e-mail"
      message: "Your message"
    errors:
      locale: "en"
      empty_name: "Name is required"
      empty_email: "Email is required"
      invalid_email: "Email is invalid"
      empty_message: "Message is required"
    after_send:
      title: "Message sent!"
      message: "Thank you for sending me a message. I'm going to answer ASAP."

analyitcsUrl: "http://stats.geekmachine.info/analytics"


collections:
  authors:
  